version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    envfile:
      - .env
    environment:
      MYSQLROOTPASSWORD: ${MYSQLROOTPASSWORD}
      MYSQLDATABASE: ${MYSQLDATABASE}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
    ports:
      - "8087:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
web:
    build: .
    ports:
      - "8086:8086"
    environment:
      MYSQLHOST: db
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      MYSQLDB: ${MYSQLDATABASE}
      MYSQLPORT: 3306
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  db_data: