name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fonte
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t danilobenedetti/app_crud_flask:latest .

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push danilobenedetti/app_crud_flask:latest

      - name: Enviar docker-compose.yml via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/danilo/deploy/docker-compose.yml"

      - name: Enviar .env via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ".env"
          target: "/home/danilo/deploy/.env"

      - name: Executar deploy remoto via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/danilo/deploy
            docker-compose down
            docker-compose pull
            docker-compose up -d --build