name: CI/CD Pipeline

on: push: branches: - main #

jobs: build: runs-on: ubuntu-latest

services:
  db:
    image: mysql:8.0
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    ports:
      - 3306:3306
    options: &gt;-
      --health-cmd="mysqladmin ping -h localhost"
      --health-interval=30s
      --health-timeout=10s
      --health-retries=5
    # Volume transient (dura s칩 o workflow)
    volumes:
      - db_data:/var/lib/mysql

steps:
- name: Checkout c칩digo fonte
  uses: actions/checkout@v2

- name: Configurar QEMU (caso build multi-arquitetura)
  uses: docker/setup-qemu-action@v1

- name: Build Docker image
  run: |
    docker build -t danilobenedetti/app_crud_flask:latest .

- name: Logar no Docker Hub
  uses: docker/login-action@v2
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

- name: Push Docker image para Docker Hub
  run: |
    docker push danilobenedetti/app_crud_flask:latest

# ====== DEPLOY REMOTO ======

    - name: Garantir que o diret칩rio de deploy existe
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: 201.23.3.86
        username: aluno
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          mkdir -p /home/danilo/deploy

- name: Enviar docker-compose.yml por SCP
  uses: appleboy/scp-action@v0.1.0
  with:
    host: 201.23.3.86              # Altere se o IP mudar
    username: aluno                # Substitua aqui pelo usu치rio REAL no servidor!!
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    source: "docker-compose.yml"
    target: "/home/danilo/deploy"  

- name: Executar deploy remoto via SSH
  uses: appleboy/ssh-action@v0.1.0
  with:
    host: 201.23.3.86
    username: aluno
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    script: |
      cd /home/danilo/deploy
      docker-compose down
      docker-compose pull
      docker-compose up -d --build
