name: Deploy SCP com SSH Agent

on:
  push:
    branches: [ "main" ]


jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar chave SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Testar conexão SSH (debug opcional)
      run: ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 'echo "Conexão ok pelo runner!"'

    - name: Enviar arquivo via SCP
      run: scp -o StrictHostKeyChecking=no requirements.txt aluno@201.23.3.86:/home/aluno/

